# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mdupont/experiments/introspector-wiki-server

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mdupont/experiments/introspector-wiki-server

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mdupont/experiments/introspector-wiki-server/CMakeFiles /home/mdupont/experiments/introspector-wiki-server/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mdupont/experiments/introspector-wiki-server/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named introspector-wiki-server

# Build rule for target.
introspector-wiki-server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 introspector-wiki-server
.PHONY : introspector-wiki-server

# fast build rule for target.
introspector-wiki-server/fast:
	$(MAKE) -f CMakeFiles/introspector-wiki-server.dir/build.make CMakeFiles/introspector-wiki-server.dir/build
.PHONY : introspector-wiki-server/fast

# target to build an object file
boost.o:
	$(MAKE) -f CMakeFiles/introspector-wiki-server.dir/build.make CMakeFiles/introspector-wiki-server.dir/boost.o
.PHONY : boost.o

# target to preprocess a source file
boost.i:
	$(MAKE) -f CMakeFiles/introspector-wiki-server.dir/build.make CMakeFiles/introspector-wiki-server.dir/boost.i
.PHONY : boost.i

# target to generate assembly for a file
boost.s:
	$(MAKE) -f CMakeFiles/introspector-wiki-server.dir/build.make CMakeFiles/introspector-wiki-server.dir/boost.s
.PHONY : boost.s

# target to build an object file
connection.o:
	$(MAKE) -f CMakeFiles/introspector-wiki-server.dir/build.make CMakeFiles/introspector-wiki-server.dir/connection.o
.PHONY : connection.o

# target to preprocess a source file
connection.i:
	$(MAKE) -f CMakeFiles/introspector-wiki-server.dir/build.make CMakeFiles/introspector-wiki-server.dir/connection.i
.PHONY : connection.i

# target to generate assembly for a file
connection.s:
	$(MAKE) -f CMakeFiles/introspector-wiki-server.dir/build.make CMakeFiles/introspector-wiki-server.dir/connection.s
.PHONY : connection.s

# target to build an object file
webem.o:
	$(MAKE) -f CMakeFiles/introspector-wiki-server.dir/build.make CMakeFiles/introspector-wiki-server.dir/webem.o
.PHONY : webem.o

# target to preprocess a source file
webem.i:
	$(MAKE) -f CMakeFiles/introspector-wiki-server.dir/build.make CMakeFiles/introspector-wiki-server.dir/webem.i
.PHONY : webem.i

# target to generate assembly for a file
webem.s:
	$(MAKE) -f CMakeFiles/introspector-wiki-server.dir/build.make CMakeFiles/introspector-wiki-server.dir/webem.s
.PHONY : webem.s

# target to build an object file
wikiserver.o:
	$(MAKE) -f CMakeFiles/introspector-wiki-server.dir/build.make CMakeFiles/introspector-wiki-server.dir/wikiserver.o
.PHONY : wikiserver.o

# target to preprocess a source file
wikiserver.i:
	$(MAKE) -f CMakeFiles/introspector-wiki-server.dir/build.make CMakeFiles/introspector-wiki-server.dir/wikiserver.i
.PHONY : wikiserver.i

# target to generate assembly for a file
wikiserver.s:
	$(MAKE) -f CMakeFiles/introspector-wiki-server.dir/build.make CMakeFiles/introspector-wiki-server.dir/wikiserver.s
.PHONY : wikiserver.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... introspector-wiki-server"
	@echo "... rebuild_cache"
	@echo "... boost.o"
	@echo "... boost.i"
	@echo "... boost.s"
	@echo "... connection.o"
	@echo "... connection.i"
	@echo "... connection.s"
	@echo "... webem.o"
	@echo "... webem.i"
	@echo "... webem.s"
	@echo "... wikiserver.o"
	@echo "... wikiserver.i"
	@echo "... wikiserver.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

